### ISSUE TITLE
Auth issue

### ISSUE THREAD

**Issue by dly9014** [nicholasjconn/python-alexa-voice-service#1]
Hi Nick, thanks for the great work, I'm hoping to get it running. The issue I'm facing is when I execute 'python main.py' and then go to 'http://localhost:5000' in a browser, I get the following error from amazon:

"... Error Summary
400 Bad Request
The redirect URI you provided has not been whitelisted for your application. Please add your redirect URI in the 'Allowed Return URLs' section under 'Web Settings' for your Security Profile on Amazon Developer Portal."

In my security profile for AVS, in 'Allowed Origins', I have included 'http://localhost:5000'. In 'Allowed Return URLs', I have included 'http://localhost:5000/authresponse'. 

However, I note that when I hover over the question mark for 'Allowed Origins', I read: "...Origins must use the HTTPS protocol... ". Also, the directions in[https://github.com/amzn/alexa-avs-raspberry-pi](url) in section 6.1 specify using https. 

So I'm not able to authenticate. How did you manage through this?  thanks

**Comment by dly9014** [comment]
I found the silly issue, I had been following [https://github.com/amzn/alexa-avs-raspberry-pi](url) and so  in In 'Allowed Return URLs', I put 'http://localhost:5000/authresponse', instead of http://localhost:5000/code' as I should have. 

So it didn't have anything to do with HTTP vs HTTPS and auth works fine. 

I don't have it running yet, first attempt yielded: 

C:\Users\young_000\OneDrive\Code\Echo\python-alexa-voice-service>python main.py
Press enter anytime to start recording (or 'q' to quit).Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\young_000\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\young_000\AppData\Local\Programs\Python\Python35-32\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Users\young_000\OneDrive\Code\Echo\python-alexa-voice-service\alexa_device.py", line 181, in device_thread_function
    process_response_handle=self.process_response)
  File "C:\Users\young_000\OneDrive\Code\Echo\python-alexa-voice-service\alexa_communication.py", line 178, in __init__
    self.init_connection()
  File "C:\Users\young_000\OneDrive\Code\Echo\python-alexa-voice-service\alexa_communication.py", line 200, in init_connection
    print("PUSH" + data.read())
TypeError: Can't convert 'bytes' object to str implicitly

You can start talking now...
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    user_input_loop(alexa_device)
  File "main.py", line 30, in user_input_loop
    alexa_device.user_initiate_audio()
  File "C:\Users\young_000\OneDrive\Code\Echo\python-alexa-voice-service\alexa_device.py", line 203, in user_initiate_audio
    stream_id = self.alexa.start_recognize_event(raw_audio)
AttributeError: 'NoneType' object has no attribute 'start_recognize_event'

**Comment by nicholasjconn** [comment]
Glad you were able to work it out!

**Comment by xubidor** [comment]
How did you solve the:

TypeError: Can't convert 'bytes' object to str implicitly
and
AttributeError: 'NoneType' object has no attribute 'start_recognize_event'

I press Enter, Talk and then what?  It just seems to time out and give me these errors.  

`ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
Press enter anytime to start recording (or 'q' to quit).Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/caleb/python-alexa-voice-service/alexa_device.py", line 181, in device_thread_function
    process_response_handle=self.process_response)
  File "/home/caleb/python-alexa-voice-service/alexa_communication.py", line 178, in __init__
    self.init_connection()
  File "/home/caleb/python-alexa-voice-service/alexa_communication.py", line 201, in init_connection
    print("PUSH" + data.read())
TypeError: Can't convert 'bytes' object to str implicitly


You can start talking now...

Traceback (most recent call last):
  File "main.py", line 45, in <module>
    user_input_loop(alexa_device)
  File "main.py", line 30, in user_input_loop
    alexa_device.user_initiate_audio()
  File "/home/caleb/python-alexa-voice-service/alexa_device.py", line 203, in user_initiate_audio
    stream_id = self.alexa.start_recognize_event(raw_audio)
AttributeError: 'NoneType' object has no attribute 'start_recognize_event'
`
